import localFont from 'next/font/local';
import Footer from '../components/footer/Footer';
import Navbar from '../components/navbar/Navbar';

import './globals.css';

const grift = localFont({
    src: [
        {
            path: '../assets/fonts/grift/Grift-Regular.woff2',
            weight: '400',
        },
    ],
    display: 'swap',
    variable: '--font-grift',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={grift.variable}>
                <Navbar />
                {/* <SmoothScroller /> */}
                {children}
                <Footer />
            </body>
        </html>
    );
}
