import localFont from "next/font/local";
import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";

import "./globals.css";

const grift = localFont({
  src: [
    {
      path: "../assets/fonts/grift/Grift-Regular.otf",
      weight: "400",
    },
  ],
  display: "swap",
  variable: "--font-grift",
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Viewport export for better mobile performance
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#0f0f0f",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
    <head>
        {/* Preconnect to external resources if any */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
      </head>
      <body className={grift.variable} cz-shortcut-listen="true">
        <Navbar />
        {/* <SmoothScroller /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
